### ISSUE TITLE
Current page 5, the download rate

### ISSUE THREAD

**Issue by jpivarski** [matthewfeickert/talk-analysis-ecosystems-workshop-2022#1]
Let's use the MacOS + Windows version of this, which avoids the question of what the intermittent bumps are. (They're big jobs on Linux that pip-install as a first step.) Also, you can enter into it in two steps, the first of which gives just the total download rate of all packages, and the second breaks it down by package, which is less overwhelming.

![pip-macwin-scikithep-log-for-report-2](https://user-images.githubusercontent.com/1852447/167896077-c906b446-a179-47d5-8977-2496a8e5cfdf.svg)
![pip-macwin-scikithep-log-for-report](https://user-images.githubusercontent.com/1852447/167896120-d485f536-7d3b-4e94-b3f9-b4f3a8bd1318.svg)

These are SVG, so you can edit out the DIANA/HEP, IRIS-HEP time ranges, and the 50× if you want to. (It doesn't take much to remove lines in Inkscape. You could even open it in an XML-aware text editor and remove elements that way. Removing is always easier than adding.)

**Comment by matthewfeickert** [comment]
Thanks @jpivarski. As I like to always hyperlink every image in my talk to its original source (assuming I didn't make it for that talk) can you link me to the GitHub repo where you made these?

**Comment by jpivarski** [comment]
These were made off-the-cuff in the rush to get the review talk written. They can be sourced here (this can be the first place they appear).
